from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List


from .investigation_report import InvestigationReportGenerator


class InvestigationReportExporter:
    """Export and manage Pro investigation reports."""

    DEFAULT_EXPORT_DIRECTORY = "exports"

    def __init__(
        self,
        generator: InvestigationReportGenerator | None = None,
        export_directory: str | Path = DEFAULT_EXPORT_DIRECTORY,
    ) -> None:
        self.generator = generator or InvestigationReportGenerator()
        self.export_directory = Path(export_directory)

    def export_markdown(self, investigation: Any) -> Path:
        """Export an investigation as Markdown."""
        path = self._build_path(investigation, "md")
        return self.generator.write_markdown(investigation, path)

    def export_json(self, investigation: Any) -> Path:
        """Export an investigation as JSON."""
        path = self._build_path(investigation, "json")
        return self.generator.write_json(investigation, path)

    def export_all(self, investigation: Any) -> Dict[str, Path]:
        """Export all currently supported report formats."""
        return {
            "markdown": self.export_markdown(investigation),
            "json": self.export_json(investigation),
        }

    def list_exports(self, investigation: Any) -> List[Path]:
        """
        Return report files belonging to an investigation.

        Only Markdown and JSON reports generated by this exporter are
        considered. Results are sorted by filename for deterministic output.
        """
        self.export_directory.mkdir(
            parents=True,
            exist_ok=True,
        )

        safe_id = self._safe_investigation_id(investigation)

        pattern = f"investigation_{safe_id}.*"

        paths = [
            path
            for path in self.export_directory.glob(pattern)
            if path.is_file()
            and path.suffix.lower() in {".md", ".json"}
        ]

        return sorted(paths, key=lambda path: path.name.lower())

    def read_markdown(self, path: str | Path) -> str:
        """
        Read an exported Markdown report.

        The requested path must remain inside the configured export
        directory and must have a Markdown extension.
        """
        safe_path = self._validate_export_path(path, ".md")
        return safe_path.read_text(encoding="utf-8")

    def delete_export(self, path: str | Path) -> bool:
        """
        Delete an exported report.

        Returns True when a file was deleted and False when it did not exist.
        The target must remain inside the configured export directory and
        must be a supported report format.
        """
        safe_path = self._validate_export_path(
            path,
            allowed_extensions=(".md", ".json"),
        )

        if not safe_path.exists():
            return False

        safe_path.unlink()
        return True

    def report_exists(
        self,
        investigation: Any,
        extension: str,
    ) -> bool:
        """Return whether a report exists for an investigation."""
        return self._build_path(
            investigation,
            extension,
        ).exists()

    def _build_path(
        self,
        investigation: Any,
        extension: str,
    ) -> Path:
        normalized_extension = str(extension).lower().lstrip(".")

        if normalized_extension not in {"md", "json"}:
            raise ValueError(
                "Unsupported report extension. "
                "Expected 'md' or 'json'."
            )

        safe_id = self._safe_investigation_id(investigation)

        self.export_directory.mkdir(
            parents=True,
            exist_ok=True,
        )

        return self.export_directory / (
            f"investigation_{safe_id}.{normalized_extension}"
        )

    def _safe_investigation_id(self, investigation: Any) -> str:
        investigation_id = str(
            getattr(
                investigation,
                "investigation_id",
                "investigation",
            )
        )

        safe_id = "".join(
            character
            if character.isalnum() or character in "-_."
            else "_"
            for character in investigation_id
        ).strip("._")

        return safe_id or "investigation"

    def _validate_export_path(
        self,
        path: str | Path,
        allowed_extensions: str | tuple[str, ...],
    ) -> Path:
        if isinstance(allowed_extensions, str):
            allowed = {allowed_extensions.lower()}
        else:
            allowed = {
                extension.lower()
                for extension in allowed_extensions
            }

        candidate = Path(path)

        if candidate.suffix.lower() not in allowed:
            raise ValueError(
                "Unsupported report file type."
            )

        export_directory = self.export_directory.resolve()

        if candidate.is_absolute():
            resolved = candidate.resolve()
        else:
            resolved = (
                self.export_directory / candidate
            ).resolve()

        try:
            resolved.relative_to(export_directory)
        except ValueError as exc:
            raise ValueError(
                "Report path must remain inside the configured "
                "export directory."
            ) from exc

        return resolved


__all__ = ["InvestigationReportExporter"]
